### ISSUE TITLE
OutputDebug command not working

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#1]
`OutputDebug "text"`

"Text" does not appear in DEBUG CONSOLE

Also, Thank You very much for your work.  I have been using SciTE4AutoHotkey for many years but sad to not have Conditional Breakpoints.

**Comment by zero-plusplus** [comment]
**I am translating from Japanese to English with Google Translate.**

Thank you for reporting.
The output feature to the debug console using `OutputDebug` has already been implemented in the develop branch.
It also implements a feature to output not only text but an object as an option.

Please be patient as we will release version 1.3.0 as soon as testing is complete.


I used to support conditional breakpoints on SciTE4AutoHotkey in the old days, but it was very difficult to use because there is no dedicated UI like vscode.

**Comment by zero-plusplus** [comment]
1.3.0 has been released. Please check if the problem has been fixed.

**Comment by SAbboushi** [comment]
Excellent!!  Very pleased with your work.  Thank you
