### ISSUE TITLE
Support inheriting completion items from base objects

### ISSUE THREAD

**Issue by thqby** [zero-plusplus/vscode-autohotkey-debug#104]
![image](https://user-images.githubusercontent.com/28240311/122659527-a9019c80-d1ab-11eb-932c-428d1f69a5f8.png)
code:
```
a := Buffer(10)
```
Members `ptr` and `size` can access it directly from `a`

**Comment by zero-plusplus** [comment]
**Translated by [DeepL translation](https://www.deepl.com/translator).**

It seems that when I implemented completion, I forgot to support inheritance.

I' m currently stopping the addition of new features, but will consider this a bug and work on it as a priority.

**Comment by zero-plusplus** [comment]
Fixed to show inherited members in develop branch.

The fix will be released after the confirmation process is completed.
It will be done by today at the earliest, and within a few days at the latest.

**Comment by thqby** [comment]
Great! An object also can access an element as `object['key']` in v2_h.

**Comment by zero-plusplus** [comment]
Thanks!
The latest version of v2_h seems to be a108, and since the latest version of v2 is a137, the specification has changed a lot.

---

The `object["key"]` suggestion process used to auto-suggest when you entered `[`, but now it only suggests when you press `Ctrl + Space` while `["` or `['` is entered.

This is to avoid unnecessary suggestions when writing arrays, and to simplify the process.
This specification is based on JavaScript.

**Comment by thqby** [comment]
The latest version of v2_h is a122, i have merge a137 into ahk_h.

**Comment by zero-plusplus** [comment]
Thanks for the info.
I am not familiar with AutoHotkey_H and it seems to be old information.

**Comment by zero-plusplus** [comment]
It took me a while to figure out how to use the vscode API.

Please wait a little longer for the release.

**Comment by zero-plusplus** [comment]
I just released the latest version.
It took a long time because the suggestion process with bracket notation like `myMap["key"]` has become complicated.

Please report back if you find any bugs.
Thanks for the report.
