### ISSUE TITLE
observed variables update very slowly while debugging

### ISSUE THREAD

**Issue by sswwaagg** [zero-plusplus/vscode-autohotkey-debug#107]
why is it that variables in the debugger pane seem to update so abysmally slow, like with a half a second delay basically
![a137slowdebugger](https://user-images.githubusercontent.com/45486372/122683630-cb71d500-d200-11eb-96db-2e2ad6527ff7.gif)
here im single stepping through some code. contrast it with the Watch Variables ive manually added - they update as soon the expression is evaluated(almost instantly), whereas the variables in the active debugger pane do not

this is on a fresh VSCode with no extensions other than `zero-plusplus.vscode-autohotkey-debug v1.6.9`
running AHKv2 a137 x64 if it matters
```
Version: 1.57.1 (system setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z (3 days ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by zero-plusplus** [comment]
**Translated by [DeepL translation](https://www.deepl.com/translator).**

This is due to the difference in processing.

The watch expression applies the update process one by one in the order. Therefore, each process is very fast.

Data inspection, on the other hand, involves many updates at once (you can't see it in the image, but many global variables are being updated).

In addition, the reason why data inspection is not updated when step execution occurs in succession is simply because the processing is longer than the step execution interval.

Finally, the update speed of the data inspection is almost the same as that of JavaScript, so it seems that this extension is not particularly slow.

**Comment by sswwaagg** [comment]
> update speed of the data inspection is almost the same as that of JavaScript, so it seems that this extension is not particularly slow.

i dont do js debugging so i got no frame of reference of what _"normal"_ debugging speed is supposed to look like, but if it is like u say, then nothing can be done about it

i guess ill stick to setting up Watches
