### ISSUE TITLE
`useAutoJumpToError` is hard to find the position after the error jump.

### ISSUE THREAD

**Issue by zero-plusplus** [zero-plusplus/vscode-autohotkey-debug#129]
Find a way to highlight the error location after the jump.

The two current suggestions are as follows.
1. select the line where the error occurred. This is easy to implement, but the viewability depends on the length of the error line.
2. highlight the error line as if it were a debug break highlight

**Comment by SAbboushi** [comment]
If you are looking for feedback, can you please provide more details e.g. screenshots or mock screenshots to show what you mean

If these are notes for yourself, then please ignore this post.

**Comment by zero-plusplus** [comment]
I didn't explain it well enough.
Issues is part of the content of CHANGELOG, so please continue to point out any areas that are difficult to understand.

---

This issue occurs when you are not using the feature to highlight the current line.
If you are not using it, you need to rely on the small blinking caret to find it.

**Comment by SAbboushi** [comment]
>> This issue occurs when you are not using the feature to highlight the current line.

Are you referring to a feature of your extension or a feature of vscode?

I customize vscode settings to make the "current line" more visible:
![image](https://user-images.githubusercontent.com/1964198/131250736-01be7feb-c23b-4fd8-a8c7-6e9e24cd674a.png)

For lines that are long enough to wrap, only the line with caret is highlighted, not the entire wrapped line:
![image](https://user-images.githubusercontent.com/1964198/131250841-a095a7a0-86c8-4d78-b286-c805a3621a49.png)

Since vscode already has this feature to highlight the current line that containts the caret, maybe your documentation can refer to vscode setting "editor.lineHighlightBackground" if the user has difficulty locating the current line?

**Comment by zero-plusplus** [comment]
Yes, I was referring to editor.lineHighlightBackground.
Thank you for researching that.

I don't use that setting because I personally find it hard to see.

There are probably other users who do not use this setting besides me, so it needs to be improved for them.

The `Go to Definition` command is what I am referring to now to solve this issue.
This command jumps to the source of the definition and highlights the text of the jump destination for about 0.5 seconds.
