### ISSUE TITLE
OutputDebug and v1.8.0

### ISSUE THREAD

**Issue by anonymous1184** [zero-plusplus/vscode-autohotkey-debug#142]
Again thanks for all the dedication to the project, but seems like the last release has an issue that in conjunction with the actual features make some not-so-welcomed additions (because they are not bug _per se_).

1. First the fact that `OutputDebug` doesn't automatically add a line feed: I see how that can be useful and treated like a feature others lack. Having an option to be consistent with others would be nice.

![20210923220455](https://user-images.githubusercontent.com/53758552/134611986-ca7e94dc-1f02-4fff-8bfa-bb4d948efdef.png)

vs

![20210923220554](https://user-images.githubusercontent.com/53758552/134612020-e276a987-2448-43d6-8002-c78af2b16adb.png)

2. Why the extension adds the command line? I mean, is kinda redundant after a few times, let alone using the extension for months; when debugging a large project you see it over a hundred times a day, it really is not needed at all given that the debug panel and the status bar show the profile you're working with.

3. It now adds `Debugging stopped.` which again is redundant: the status bar of VSCode changes color when debugging, and changes back when it finishes giving a perfect indicator when the debugging session has finished.

4. The exit code is very useful but only when is other than `0`, now is displayed always.

In other words, printing a single value will show 3 other lines:

![20210923224226](https://user-images.githubusercontent.com/53758552/134614751-d6c4e111-2ca7-44c9-b51c-ca9ba2cc55c9.png)

And there's a "bug" (a lack of a better word) with non-zero exit codes:

![20210923223000](https://user-images.githubusercontent.com/53758552/134614805-d86d9aba-9f11-41da-b644-62ac45e87355.png)

vs

![20210923223013](https://user-images.githubusercontent.com/53758552/134614823-23e29ff8-9dbb-4b00-87de-bc0280947c26.png)

Still, I'm very grateful for all the work you have poured into this. Perhaps my rationale isn't fit for everyone... options for disabling the behaviors would be very nice, even if they are under the hood rather than in the UI. That or a little guidance on where to edit the extension to recompile it; I haven't done anything with extensions but I'm comfortable around code.

**Comment by zero-plusplus** [comment]
I would like to conclude that verbose messages are to let beginners know what is going on, which is the policy of this extension.

However, for those who do not need them, it would be preferable to be able to set whether or not they are displayed by themselves.

I will consider adding these settings. However, I can't think of a good option name, so if you have an idea, please let me know.

---

Below are the individual answers.

> First the fact that OutputDebug doesn't automatically add a line feed: I see how that can be useful and treated like a feature others lack. Having an option to be consistent with others would be nice.

This specification is compliant with SciTE4AutoHotkey. Also, the line feeds are intentionally not included because if the debugger adapter adds them, the user cannot control them.

I have considered options related to line breaks, but had to hold off because I couldn't come up with a clear option name.

When adding options, it might be good to also add an option to change the color of the output; VSCode allows three different colorings: blue (stdout), red (stderr), and yellow (console).

> Why the extension adds the command line? I mean, is kinda redundant after a few times, let alone using the extension for months; when debugging a large project you see it over a hundred times a day, it really is not needed at all given that the debug panel and the status bar show the profile you're working with.

This was based on the SciTE4AutoHotkey specification and the Node.js debugger specification.

It is to report the start of debugging and to check the details of the startup configuration.
Also, it is useful as a debug message when setting options that cause startup issues, such as RuntimeArgs.

> It now adds Debugging stopped. which again is redundant: the status bar of VSCode changes color when debugging, and changes back when it finishes giving a perfect indicator when the debugging session has finished.

I have enabled the disconnect feature by adding the attach mode from 1.8.0. As a result, there are four termination patterns, and I am displaying a message to notify you of them.

I understand that these are redundant messages for advanced users, so it would be nice to have an option to not show these. However, the name of the option needs to be easy to understand.

> The exit code is very useful but only when is other than 0, now is displayed always.

This was always displayed at first. It is a bug that it did not show up. I needed it, but it is a redundant message, so it would be nice if it could be set as an option as in the answer above.

---

The last images shows the specification of VSCode, which has three categories: stdout, stderr, and console, and if another category is output, it will be output on a different line even if it does not contain a newline.

**Comment by zero-plusplus** [comment]
I added a new attribute to launch.json that solves this issue. This will take effect in the next release.

This solves your issue in the follows way.
> 1. First the fact that OutputDebug doesn't automatically add a line feed: I see how that can be useful and treated like a feature others lack. Having an option to be consistent with others would be nice.

Set the new attribute `useOutputDebug` as follows.
```
"useOutputDebug": {
    "suffix": "\n",
    "removeTrailingLinebreak": true,
}
```
‘suffix‘ is a string that is added to the end of the message. If you have mixed code that includes a newline at the end, you can use `removeTrailingLinebreak` to remove the newline.

> 2. Why the extension adds the command line? I mean, is kinda redundant after a few times, let alone using the extension for months; when debugging a large project you see it over a hundred times a day, it really is not needed at all given that the debug panel and the status bar show the profile you're working with.
>
> 3. It now adds Debugging stopped. which again is redundant: the status bar of VSCode changes color when debugging, and changes back when it finishes giving a perfect indicator when the debugging session has finished.
>
> 4. The exit code is very useful but only when is other than 0, now is displayed always.

Just assign `true` to the new attribute `suppressAnnounce`. Now you will not see any unnecessary announcements other than errors.

---

I have made some major changes to the source code and will be taking a lot of time for testing.
The release is to have it ready by the end of this month, but it may be delayed due to problems.

**Comment by zero-plusplus** [comment]
@anonymous1184
It took longer than expected, but this issues has been resolved in `1.10.0`.

---

> 1. First the fact that doesn't automatically add a line feed: I see how that can be useful and treated like a feature others lack. Having an option to be consistent with others would be nice.`OutputDebug`

Add the following to launch.json.
```
"useOutputDebug": {
    "useTrailingLinebreak": true,
},
```

> 2. Why the extension adds the command line? I mean, is kinda redundant after a few times, let alone using the extension for months; when debugging a large project you see it over a hundred times a day, it really is not needed at all given that the debug panel and the status bar show the profile you're working with.
>
> 3. It now adds which again is redundant: the status bar of VSCode changes color when debugging, and changes back when it finishes giving a perfect indicator when the debugging session has finished.Debugging stopped.
>
> 4. The exit code is very useful but only when is other than , now is displayed always.`0`

Add the following to launch.json.
```
"useAnnounce": "error",
```

**Comment by RaptorX** [comment]
Are those going to be options that could be controlled in the Extension settings at some point? or at least to be able to modify `settings.json`?

When creating very simple scripts I do not use the `launch.json` file and would still like to be able to have those options enabled. Basically I would have to be able to set some default options to be launched every time even if I havent setup a debugging environment for the current script.

**Comment by zero-plusplus** [comment]
You can set up a global debug configuration by adding `launch` to settings.json.

Try pasting the following into settings.json as a test.

```
"launch": {
  "configurations": [
    {
      "name": "AutoHotkey Debug (Global)",
      "type": "autohotkey",
      "request": "launch",
      "program": "${file}",
      "args": []
    },
  ]
},
```

**Comment by RaptorX** [comment]
While it is true that I can use this approach it seems like due to issue #242 the settings are being ignored and that's the reason I thought that was not possible.

**Comment by Norlandz** [comment]
> Add the following to launch.json.
> 
> ```
> "useOutputDebug": {
>     "useTrailingLinebreak": true,
> },
> ```

As of now, I use the following config, and it works.

```
{
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "AutoHotkey Debug (Advanced Configuration)",
      "type": "autohotkey",
      "request": "launch",
      "program": "${file}",
      "args": [],
      "port": "9002-9010",
      "variableCategories": "recommend",
      "useDebugDirective": true,
      "useAutoJumpToError": true,
      "useOutputDebug": {
        // "suffix": "\n",
        // "removeTrailingLinebreak": true,
        "useTrailingLinebreak": true,
      }
    }
  ]
}
```

![image](https://github.com/user-attachments/assets/9e1b88c1-0298-4056-bcc3-2d7fb9e68501)

Having `AutoHotkey v2 Language Support by thqby` at the same time is ok-ish. 
Just make sure you **click and run from the debug panel**, not by keyboard hotkey, nor by clicking the icon on top right of your ahk file.

**Comment by zero-plusplus** [comment]
Thanks for the information. I was concentrating on my project and my reply was delayed.

It was so long ago that I don't remember much, but after checking the above issues(#242), it seems that the problem was not a conflict issue, but rather that the debugging was initiated using the default debugging settings of the collaborating extension.

It was due to the default shortcut key (F5) being overwritten by the collaborating extension, so as you say, you can start debugging directly from the debug panel and it will work fine. (It's been a long time, so the shortcut key issue may have been resolved if it's been reported.)
