### ISSUE TITLE
[a112] Hyperlink to warning line

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#15]
Line number is not included in hyperlink. 

![image](https://user-images.githubusercontent.com/1964198/85211888-0e118080-b313-11ea-88e6-5c3755106059.png)

Also, wondering about why warning is duplicated?

**Comment by zero-plusplus** [comment]
I want to make sure of two things.
1. the version that is occurring
2. whether or not it will always occur when executed under the same conditions

Let's talk about why you're asking this.
1. because the recent AutoHotkey update has changed the source code of the debugger, and I want to see if the bug is due to a spec change
2. I have encountered the same bug. But it wasn't always going to happen, so I've been holding off on fixing it. I want to see if this bug is the same as that one

**Comment by zero-plusplus** [comment]
I confirmed with SciTE4AutoHotkey, but the same problem occurred.

Probably a bug in the AutoHotkey debugger.

**Comment by SAbboushi** [comment]
thanks for the information
