### ISSUE TITLE
Unnecessary feature_get and feature_set commands

### ISSUE THREAD

**Issue by Lexikos** [zero-plusplus/vscode-autohotkey-debug#164]
Whenever the variable list is retrieved, the extension sends something like the following:
```
feature_get -n max_depth
feature_set -n max_depth -v 1
context_get -c 1 -d 0
feature_set -n max_depth -v 1
```
Three of these commands are unnecessary, because the first command sent upon connection (at least with "attach") was:
```
feature_set -n max_depth -v 1
```
max_depth and other variables that can be set by feature_set only apply to the debugger. They are changed from their default values only when the client sends feature_set, and there can only be one client at a time. 

Therefore, once you set max_depth to 1, you know for certain that it has that value until you set it to something else. There is no need to query it, or to set it to the value it already has.

These extra commands add a small amount of latency, and add noise that makes debugging the debugger itself more difficult.

**Comment by zero-plusplus** [comment]
This was implemented with the intention of using maxDepth. I was a bit tired at the time, so I remember implementing it rather sloppily.

We didn't end up using it at the time, but it will be used to fix the issue in #146.

The three useless commands pointed out above will be fixed so that they are only executed if maxDepth is used.

I forgot to refactor here, so this was a help. I've recorded it in #144 so I don't forget.
