### ISSUE TITLE
Watches and hover not respecting the current call stack selection

### ISSUE THREAD

**Issue by Lexikos** [zero-plusplus/vscode-autohotkey-debug#166]
When I select a call stack entry, I would expect the *Locals*, *Watch* and hover to then show values according to the context (stack depth) of the entry I selected. Instead, only *Locals* shows the appropriate values. *Watch* and hover show only the values of the current (topmost) function or "not available".

**Comment by Lexikos** [comment]
Erk, this is probably a duplicate of #149, which I already had open in another tab. I must have spaced out.

**Comment by zero-plusplus** [comment]
OK.

On a related note, I noticed that when the `d` option of property_get is set to the AutoExec section, it returns the variables of the latest call stack.

For example, suppose break at `b` in the following case.
```ahk
a()
a() {
  localVar := A_ThisFunc
  b()
}
b()
{
  localVar := A_ThisFunc
  ; @Debug-Breakpoint
}
```

The following command will return `b` instead of `undefined`.
```
property_get -i 1 -n localVar -c 0 -d 2
```

On the other hand, the following command returns `a` successfully.
```
property_get -i 1 -n localVar -c 0 -d 1
```
