### ISSUE TITLE
Debugger request long time for initialing since v1.10.0

### ISSUE THREAD

**Issue by aseiot** [zero-plusplus/vscode-autohotkey-debug#199]
launch.json

       {
          "version": "0.2.0",
          "configurations": [
              {
                  "name": "AutoHotkey v2 Debugger",
                  "type": "autohotkey",
                  "request": "launch",
                  "port": "9002-9010",
                  "program": "${file}",
                  "runtime": "${workspaceFolder}/AutoHotkey.exe",
                  "runtimeArgs" :[
                      "/ErrorStdOut"
                  ],
                  "stopOnEntry": true,
                  "openFileOnExit":"${file}",
                  "useAutoJumpToError": true,
                  "useIntelliSenseInDebugging": false
              }
          ]
       }

Following demonstrate debug with latest v1.10.2, which need waiting for very long time to first run. This happened since v1.10.0, and right now I must return back to v1.9.0.
![](https://user-images.githubusercontent.com/600263/152514964-e95f7bcb-c16b-438d-ad16-62a9750088c3.gif)

Other feature I would like to request is parsing include lib path based on the "runtime". It is said "directory-of-the-currently-running-AutoHotkey.exe\Lib\" as instrument in AHK help. 

But I noticed that "vscode-autohotkey-debug" defined the standard library path as follow:
`export const standardLibraryDir = ``${String(process.env.ProgramFiles)}\\AutoHotkey\\lib;`

**Comment by zero-plusplus** [comment]
I just noticed a misunderstanding about the Standard library. Thank you.

I will fix it as soon as I have time.

**Comment by zero-plusplus** [comment]
I checked the issue with the file structure that I guessed from the image and could not find the issue.

Another issue that I found was that if the path to AutoHotkey.exe was wrong, debugging would not start or end as shown in the image.

Therefore, please let me know the file structure that you have open in VSCode so that I can check if there is any mistake in the path.

---

Initially, I thought the issue was caused by the wrong path to the standard library, but it seems that this is not the cause of the issue, as it did not cause any issues other than the library not appearing in the `loaded scripts`.

**Comment by aseiot** [comment]
Thanks for your responding, my path is just as the image I have posted, and I don't think it is issue with path, cause if I switch back to v1.9.0 then everything would be ok. 

The another thing is that I have fetched the source code of this extension, and if I run the demo code, that seems initialized instantly.
![](https://user-images.githubusercontent.com/600263/152627840-08ffd08a-21a1-4f3f-ae07-dfed144f9cc3.gif)

**Comment by zero-plusplus** [comment]
Thank you, if it works for v1.9.0, it seems that the path is not misspecified.

> that seems initialized instantly.

What does this mean? Does it mean that the demo code can run without issue?

---

I have not yet been able to confirm this issue, so if you don't mind, can you provide the minimal project folder where this issue occurs?

**Comment by aseiot** [comment]
Yes, the demo code run without issue.
My project is really a big one with a lot of library dependency, and as I have said it will be eventually successfully launched after long time waiting. Thus I have debugged the extension, and if I pause during the initial step, it stop at the process of extract lib dependency. That is why I asked to solve the parser of standard library path. Following demonstrated the snap of image when I press "pause" during the debugger initialization.
![image](https://user-images.githubusercontent.com/600263/152632794-da9c8f6b-69fd-4c05-ba06-864564e0783b.png)

**Comment by aseiot** [comment]
Call stack shows thousands of extract actions.
![image](https://user-images.githubusercontent.com/600263/152632941-c683ce3a-045c-479f-9083-107b67dbb88c.png)

**Comment by zero-plusplus** [comment]
Thanks for looking into it. Thanks to you, I understand the issue.

I guess it is taking a long time because it is reanalyzing the libraries it has already read without caching them.

I will release a fixed version within a week, but I may not have time to fix it as much as I would like. Until then, please use 1.9.0.

**Comment by zero-plusplus** [comment]
Fixed this issue in `#199-fixed` branch.

Please clone this branch or `develop` branch and create a vsix using the following command prompt commands and check your project to see if it fixes it correctly.

1. `npm install`
2. `npm run package`

**Comment by aseiot** [comment]
I have just tested the new develop version. Although it takes longer time then v1.9.0, the version works now and the initial time is acceptable. Thanks!

**Comment by zero-plusplus** [comment]
Thanks for testing it.
The reason why it takes so long to launch the debug is because it scans all scripts twice to make Loaded Scripts work.

Loaded Scripts is not always a necessary feature, so I suggested the option to disable it [here](https://github.com/zero-plusplus/vscode-autohotkey-debug/issues/201).

**Comment by zero-plusplus** [comment]
In the latest develop branch, I parallelized the scanning process that occurs twice in `Loaded Scripts`.
Also, added an attribute to disable the scan itself.

This should have improved the initialization speed to some extent.

Please test it if you like.

**Comment by aseiot** [comment]
Thanks, I have tried the head develop version with "useLoadedScripts" set to false, and the launch is faster now.

**Comment by zero-plusplus** [comment]
Thanks for confirming.

What is the initialization speed when the following settings are used?
```
...
{
  "useLoadedScripts": {
    "scanImplicitLibrary": false,
  },
}
...
```

**Comment by aseiot** [comment]
Still slower than v1.9.0, but is much faster than without that settings. 
I notice an odd thing that it is slower when start with "F5" than click the "Start debugging" button.

**Comment by zero-plusplus** [comment]
Thanks for trying.
I will check the source code for 1.9.0 and optimize it.

The release will be prioritized because this fix contains a bug that is fatal to some people.
After that, optimization will be done as soon as time is available. Until then, we apologize for the inconvenience, but please use `useLoadedScripts` to speed up the initialization process.

---

> I notice an odd thing that it is slower when start with "F5" than click the "Start debugging" button.

I know that restarting the debug runs faster because it reuses the previous settings (launch.json, Loaded Scripts, etc.), but I don't know what causes the difference in the initialization process other than that.

It is indeed strange.

**Comment by zero-plusplus** [comment]
I think the slower speed compared to 1.9.0 may be due to the increased accuracy of the Include path extraction.

In my project, it extracted about 60 in 1.9.0, and about 80 in 1.10.x.
