### ISSUE TITLE
[enhancement] Data inspection when click on value / rewrite value

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#20]
```
_var1 := "a`tb`nc"
```
![image](https://user-images.githubusercontent.com/1964198/87214460-61fbfd80-c2f2-11ea-8da5-e891c31f7e8c.png)

When click on value in VARIABLES Pane:
![image](https://user-images.githubusercontent.com/1964198/87214469-73450a00-c2f2-11ea-928e-efd3507182b2.png)

If I copy/paste this value, it will paste
```
"a	bc"
```

1) Possible to evaluate all escaped characters?  I would be happy for it to display like this when click on value in VARIABLES Pane:
```
a	b
c
```

2) I want to copy and paste the value so it pastes correctly (preferably without the encapsulating quotes) e.g.
When I click on value in VARIABLES Pane, I don't want to see the quotes:
```
a	b
c
```
Not like this:
```
"a	b
c"
```
2a) But if that is not possible, then maybe possible to automatically remove quotes when copy value?

**Comment by zero-plusplus** [comment]
> 1. I would be happy for it to be displayed like this when clicked on would be happy for it to display like this when click on value in VARIABLES Pane:

This is a standard feature of vscode and there's probably nothing I can do about it.
There are a few other buggy behaviors in addition to this, but it's the same in the node debugger, so I'm assuming it's a current specification.

I'll share some of the bugs I've found.
* Variable names are replaced with something else when variable rewriting fails.
* Canceling the rewriting of a variable whose value contains a newline appears to replace the value with a blank one.

> 2 I want to copy and paste the value so it pastes correctly (preferably without the encapsulating quotes) e.g.
When I click on the value in VARIABLES Pane, I don't want to see the quotes:

I'm sorry, but I can't take this request.
I have already told you that I am referring to the node debugger.
In the node debugger, if a value is not enclosed in double quotes and is not numeric, it is treated as a variable name and you can rewrite the variable according to that value.
My extension doesn't implement this, but may do so in the future, so the string has to be enclosed in double quotes.

By the way, the reason it's not implemented is because the AutoHotkey debugger doesn't support object rewriting.

> 2a) But if that is not possible, then maybe possible to automatically remove quotes when copy value?

This is also a standard feature of vscode, as in 1. It seems to me that a hook to change the behavior would help, but I haven't seen it.

I'm sorry I can't help you.

**Comment by SAbboushi** [comment]
Thank you for the explanations.

**Comment by zero-plusplus** [comment]
Do you have any other questions?
If not, please close it.

Also, did you check #21?

**Comment by SAbboushi** [comment]
Thanks - I posted a link in #21 about the need for debugger to "escape" whitespace e.g. newlines.  Will this work?

**Comment by zero-plusplus** [comment]
I'll check it out now.

**Comment by zero-plusplus** [comment]
> 2. I want to copy and paste the value so it pastes correctly (preferably without the encapsulating quotes) e.g.
When I click on value in VARIABLES Pane, I don't want to see the quotes:

A [feature](https://code.visualstudio.com/updates/v1_49#_contributable-context-menu-for-variables-view) to solve this problem has been added in vscode version 1.49.

I plan to implement this in the future.
In this case, the required version of VSCode will be changed from 1.45 to 1.49, so some users with older VSCode will not be able to use this extension.

**Comment by SAbboushi** [comment]
Thanks for update.  WOW - I hope your extension will also implement the feature to select between Binary/Decimal/Hex
