### ISSUE TITLE
[enhancement] Evaluate all escaped characters in hover data inspection

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#21]
When hover over `_var1" value in VARIABLES Pane, the tab character is not evaluated:
![image](https://user-images.githubusercontent.com/1964198/87214759-14cd5b00-c2f5-11ea-973b-d04d4d94180e.png)

**Comment by zero-plusplus** [comment]
Sorry, it's a vscode spec. So there is nothing I can do about it.

**Comment by SAbboushi** [comment]
Is this relevant? https://github.com/microsoft/vscode/issues/73845#issuecomment-582458652

I am very ignorant about developing extensions and the API: does this link say that vscode was changed so that escaping whitespace (e.g. Tab) is the job of Debugger extensions?

**Comment by zero-plusplus** [comment]
I checked.

This is about the debug console.
I don't think it's related to the tooltips that appear when hovering, as it's a different process.

**Comment by zero-plusplus** [comment]
Apparently I'm wrong about this and it's actually an issue with this extension.
In fact, you were right.
There seems to have been a change in [vscode 1.43](https://code.visualstudio.com/updates/v1_43) regarding whitespace.


I didn't recognize this problem because the JavaScript debuggers at the time didn't evaluate whitespace.
This was just not yet compatible with the vscode changes.

When I checked in the newer JavaScript debugger now, it was evaluating whitespace. This means that a newline character will be displayed as `\n`.

**Comment by SAbboushi** [comment]
Very Good!

**Comment by zero-plusplus** [comment]
I found that refactoring was needed to smart fix this problem.
Fixing it now could delay the release of 1.6.0 by several days.

Therefore, I decided to fix it in 1.6.1 or 1.7.0.
Please be patient for a while longer.

**Comment by SAbboushi** [comment]
ok thanks for update

**Comment by zero-plusplus** [comment]
I didn't do extensive refactoring because I prioritized speed.
