### ISSUE TITLE
[bug] Child element index range, Child element index 

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#25]
![image](https://user-images.githubusercontent.com/1964198/89683977-220f4280-d8bf-11ea-840a-a82c8163361f.png)

I would like if [50000] element is listed under range [50000..50039]

**Comment by SAbboushi** [comment]
Also, when setting is `"maxChildren": 10000`, is correct to show the above ranges that are >10000?

**Comment by zero-plusplus** [comment]
The array chunking headings are set to 0-based by default.
I can't find a way to change this setting, so I can't solve this problem.
I'll add a note to the README as a known problem.

Let's talk about it in more detail.
If you look [here](https://github.com/microsoft/vscode/blob/c033ceaa241f8bf94e2661ee5c4adb7f9af86be0/src/vs/workbench/contrib/debug/common/debugModel.ts#L89 
), it should be possible to change 0 base to 1 base, but I couldn't find any code in the source code in VSCode that uses `startOfVariables`, which is the argument used to set the base.
Therefore, I decided that it was not possible to change this setting from the debug adapter side.

`maxChildren` is the maximum number of child elements itself.
Perhaps they were wondering why the number of elements in an array of 10,000 would be 9999.
This is because child elements are not only elements of the array, but also include the base field and other elements in the number.
Because v2 arrays contain base fields, by default you can only get elements of arrays up to 9999.

I had the same misunderstanding, so I guess I should change the description.

**Comment by SAbboushi** [comment]
Thanks for providing the details
