### ISSUE TITLE
[Documentation] Data Inspection

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#38]
`If you want to see the data of an object, you can use the It should be a member access syntax like obj.field.`

Documentation is missing part of explanation.  Maybe you mean:
`If you want to see the data of an object, you can use the` [Debug Console REPL](https://code.visualstudio.com/Docs/editor/debugging#_debug-console-repl)

**Comment by zero-plusplus** [comment]
I've revised the text.
`Only variables, and fields that use the member access syntax (e.g. object.field) are supported.`

---
Incidentally, the Debug Console REPL is a feature that is intentionally undocumented.

The REPL is a byproduct of implementing the watch expression, because the watch expression is better in every way.

**Comment by SAbboushi** [comment]
Good
