### ISSUE TITLE
Run panes are empty when MsgBox is displayed

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#4]
```
x := 1
MsgBox 12
y := 2
```
When `MsgBox `is displayed, all the RUN panes become empty until the MsgBox "OK" button is clicked.

**Comment by zero-plusplus** [comment]
Which are the RUN panes?
![image](https://code.visualstudio.com/assets/docs/editor/debugging/debugging_hero.png)

If you are talking about `A: Debug side bar`, that is normal.
The timing at which it is displayed/updated is when a stop event is sent to vscode.

AutoHotkey is stopped by MsgBox. However, the stopped information is not notified to vscode.

This is also the case with Scite4AutoHotkey.

**Comment by zero-plusplus** [comment]
I checked again, but it was impossible due to the specifications of AutoHotkey Debugger.

Even if you stop in MsgBox, the event is not notified and the internal state seems to be `runnning` instead of `break`.

**Comment by SAbboushi** [comment]
You asked: "Which are the RUN panes?"
"B" in your screenshot.
![vscode RUN Panes (VARIABLES, CALL STACK) empty when MsgBox is displayed](https://user-images.githubusercontent.com/1964198/83965081-b08f2580-a876-11ea-9c06-b03b01042bb7.png)

You said: "This is also the case with Scite4AutoHotkey."
In my test, SciTE4AutoHotkey Variables pane and Callstack pane do not become empty during MsgBox display.  Also, clicking on the SciTE4AutoHotkey Variable list button while MsgBox is displayed refreshes the Variable list pane as you can see here:
![image](https://user-images.githubusercontent.com/1964198/83965264-ff898a80-a877-11ea-9c4b-3daa0a21a4c0.png)
![image](https://user-images.githubusercontent.com/1964198/83965278-1d56ef80-a878-11ea-9257-9edea4e9a703.png)

**Comment by zero-plusplus** [comment]
It's due to the difference in UI.

Since there is no variable list button etc. in vscode, processing using those events cannot be implemented.

What is important is the fact that information such as variables is not updated when MsgBox is displayed.
SciTE4AutoHotkey is displaying old information (in this example, the information immediately after starting). vscode will hide old information.

SciTE4AutoHotkey just updates the information when the button is pressed.
Again, vscode doesn't have that button.

The only way to get the same state is to press the pause button.
You should get the same result.

**Comment by SAbboushi** [comment]
Thanks for explaining.

>  The only way to get the same state is to press the pause button.
> You should get the same result.

Very good!

> vscode will hide old information.

I understand.  Thank you again for the explanations and your good work
