### ISSUE TITLE
Navigating to Subroutines / Functions / Methods

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#5]
Do you give permission to ask questions here?  If not, is there a way you will allow me to ask questions?

In SciTE4AutoHotkey, I can jump to Subroutines / Functions / Methods by pressing keys SHIFT/ENTER when cursor is within name of the routine.  For example in screenshot below: cursor is on Line 11 between "i" and "o" in function name "Function1()".  When I press keys SHIFT/ENTER, the cursor jumps to line 14.
![image](https://user-images.githubusercontent.com/1964198/83981369-ca665200-a8e2-11ea-8693-92a8f6914ad4.png)

Is there similar feature you can make for your extension?

Also, I can instead press `F12` key and a list of routines appears for another way to jump:
![image](https://user-images.githubusercontent.com/1964198/83981482-cd157700-a8e3-11ea-9c53-9784bb8844a0.png)

**Comment by zero-plusplus** [comment]
There is no problem because `issues` accepts questions and requests.

Labeling "question" for questions and "enhancement" for feature requests will make it easier for others to see.

Well, the main subject.
Unfortunately those features do not exist in this extension. Also, I have no plans.
Because they will be implemented in another extension that supports syntax highlighting etc.

However, this will take time.
