### ISSUE TITLE
The contents of array are displayed incorrectly

### ISSUE THREAD

**Issue by FMarks** [zero-plusplus/vscode-autohotkey-debug#71]
vscode 1.51.1 / vscode-autohotkey-debug 1.6.4 / ahk 1.1.33.02
vscode-autohotkey [have same bug](https://github.com/cweijan/vscode-autohotkey/issues/56)
```
#Requires AutoHotkey 1.1.33+

#Warn All
#SingleInstance Force
#NoEnv

SetWorkingDir %A_ScriptDir%
SetBatchLines -1

array := {}

; --- Something strange
; array[99] := "some value"
; array[100] := "now see debugger"

; Debugger show:
; ...
; array: Array(100) <-- ? incorrect array size ?
; [99]: some value
; [100]: now see debugger
; ...

; --- Something strange
array[100] := "some value"
array[101] := "now see debugger"

; Now debugger show:
; ...
; array: Array(101)
; [0..99]
;    [1]: some value
;    [2]: now see debugger
; [100..100]
; ...
```

**Comment by fade2gray** [comment]
```
array1:={99:"99",100:"100"}
array2:={100:"100",101:"101"}
array3:={1000:"1000",1001:"1001"}
pause  ; <- set breakpoint
Exit
```

![AHK-debugger](https://user-images.githubusercontent.com/1332009/99686916-f6822380-2a7b-11eb-85a6-b32aa23fcd78.PNG)

**Comment by zero-plusplus** [comment]
It is probably because of [this issue](https://github.com/zero-plusplus/vscode-autohotkey-debug/issues/25) that the notations in the pointed out sections seem strange.
This is not currently possible to fix.

However, the sparse array is marked as `Object(1001) [1000, 1001]`, which is a bug that should be fixed. It should be `Object { 1000: 1000, 1001: 1001}`.

**Comment by FMarks** [comment]
Maybe you will be interested: ['autohotkey-debug' v0.6.9](https://github.com/helsmy/autohotkey-debug-adaptor) displays contents of array correctly.
![debug](https://user-images.githubusercontent.com/40742653/99809388-42ec6280-2b53-11eb-9678-fab993a80476.png)

**Comment by zero-plusplus** [comment]
`[101]` is simply the key name of the object. It is retrieved by the AutoHotkey debugger. The `[0-99]` is generated by VSCode's collapsing feature.

The focus in this issue is the specification of the collapsing feature.
VSCode provides the ability to collapse for any number of arrays. I've set up the folding to work for large arrays over 100, following the Node debugger.

And it's important to note that labels like `[0-99]` are **automatically** given by VSCode.
I looked through the VSCode source code to find a way to change this label, but I couldn't find it.

To be precise, I found the code to change it, but I couldn't solve the problem because it doesn't seem to be exposed as an extension API.

**Comment by zero-plusplus** [comment]
Since Julia, which is also 1-base, has the same problem, I decided that the VSCode specification does not allow for a solution and I am closing this issue.

I'll label it in case VSCode is updated in the future and this issue can be resolved.
