### ISSUE TITLE
F1 jump to documentation

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#9]
Enhancement request:
`F1` key displays the AHK Documentation relevant to cursor position for AHK script version (like SciTE4AutoHotkey)

**Comment by zero-plusplus** [comment]
Similar to #5.
This extension implements only debugging functionality.

Please wait because that feature will be implemented as another extension.
However, it takes time. The project is stagnant due to the inexperienced parsing process as well as the maintenance of this extension

I plan to release the preview version in about 3 months. But this is pretty optimistic.

**Comment by zero-plusplus** [comment]
Did you see my comment?

If all your questions are resolved, please close this issue.

**Comment by SAbboushi** [comment]
I'm adding this link only to make it easier for me to find your "Jump to Document" workaround: [https://github.com/zero-plusplus/vscode-autohotkey-debug/issues/70#issuecomment-725519110](url)

**Comment by zero-plusplus** [comment]
I decided to include the document jumping feature in an early release of `vscode-autohotkey`.

This is because the document path information is included in the API definition that I am updating, which makes it easier to implement.

However, it may be difficult to release it this year because the API definition will take a lot more time than I expected.

**Comment by SAbboushi** [comment]
OK - good luck

**Comment by mark-wiemer** [comment]
See also https://github.com/vscode-autohotkey/ahkpp/issues/78
