### ISSUE TITLE
class symbols disappeared

### ISSUE THREAD

**Issue by thegamerx1** [zero-plusplus/vscode-autohotkey-debug#92]
before I could search for methods in the class but now I can't. This is from a recent update
![08_03_2021_f0ZXR](https://user-images.githubusercontent.com/34986564/110357823-feba9a80-803b-11eb-86de-aa0d471b0a0c.gif)

**Comment by zero-plusplus** [comment]
This extension does not provide any symbols.

Please uninstall this extension once to see the source of this issue.
If the issue still occurs, it is bug in another extension.

If the issue is resolved when uninstalling, try the minor versions of this extension in order (i.e. `1.6.0`, `1.5.0`, `1.4.0`, etc.).

If you still can't solve the issue, it may be a bug in a particular version of VSCode.
Or it may be a bug of my own origin due to lack of understanding of the VSCode API specification. In this case, it is very difficult to find the cause code, so a lot of time is required.

**Comment by zero-plusplus** [comment]
All good.

If you encounter any other issues, please report back. 👍
