### ISSUE TITLE
[BUG] Slow performance of conditional breakpoints, and crashes after 6000 more than uses

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#95]
I am still debugging/modifying TypeLib2AHK.ahk.  I did some testing of `useDebugDirective`.  For simple test code, it worked good but with large complex script like TypeLib2AHK.ahk with lots of lines executed, it kept terminating after maybe two minutes with:
`invalid breakpoint (the IDE tried to set a breakpoint on a line that does not exist in the file (ie "line 0" or lines past the end of the file)
`

![image](https://user-images.githubusercontent.com/1964198/111036787-ae9a5a00-83e6-11eb-958f-34170ce5af6b.png)

I have disabled `useDebugDirective` for now.  I know this is a "preview version": if you want to try and recreate at some point, this is where I placed the Debug-Breakpoint:

Add these two lines (note: the line numbers will not match the downloaded script):
```
debug1 := (obj.Name="IModules" && Name="_SaveAs")
; @Debug-Breakpoint(debug1)
```

![image](https://user-images.githubusercontent.com/1964198/111037143-7ac03400-83e8-11eb-9712-47d392ba99e3.png)

Test by selecting "Microsoft Excel 16.0 Object Library" with option to "Create AHK v2 code".

**Comment by SAbboushi** [comment]
Seems this problem may not be only related to `useDebugDirective`; I tried conditional breakpoint on debug1 and it terminated the host after maybe 2 minutes:
![image](https://user-images.githubusercontent.com/1964198/111037763-397d5380-83eb-11eb-8904-965eb9858efe.png)

It seems it terminated on or around Interface # 161:
![image](https://user-images.githubusercontent.com/1964198/111037805-6a5d8880-83eb-11eb-8430-d250c79e37ac.png)

I will continue to post any relevant findings.

**Comment by zero-plusplus** [comment]
> invalid breakpoint (the IDE tried to set a breakpoint on a line that does not exist in the file (ie "line 0" or lines past the end of the file)

In my case, I could not see the message.

This issue seems to occur when a conditional breakpoint is evaluated more than 6000 times. The evaluation speed gradually decreases and finally crashes.
This can be seen in the following simple example.
```ahk
Loop 7000 {
  ; @Debug-Output => {A_Index}
}
```

By the way, regardless of this bug, it is deprecated to use conditional breakpoints in large loops. The best solution would be to use an if statement, as in the following example. However, the source code will be a bit dirty.
```ahk
if (obj.Name="IModules" && Name="_SaveAs") {
  ; @Debug-Breakpoint
}
```

The implementation of conditional breakpoints is very complex and may be difficult to solve immediately. I will postpone the resolution of this bug because it works fine in the way it is supposed to be used.

I will try to solve it later when I do a major refactoring.

**Comment by SAbboushi** [comment]
I think the "dirty" code you suggested is best and certainly fastest solution.  Thank you!

**Comment by zero-plusplus** [comment]
I noticed that this issue does not occur in `1.6.4` and earlier.
I also noticed that the performance of conditional breakpoints was significantly degraded.

I found the issue area, and will fix it as soon.

**Comment by zero-plusplus** [comment]
I clarified the title to make it easier to capture this issue.

**Comment by zero-plusplus** [comment]
Test code for performance measurement.
```ahk
startTime_ms := A_TickCount
Loop 6000 {
  ; @Debug-Output => {A_Index}
}
elapsedTime_s := (A_TickCount - startTime_ms) / 1000
; @Debug-Output => {elapsedTime_s}s
; @Debug-Breakpoint
return
```
Measurement results.
```
1.6.4: 18s
1.6.5: 81s
```

Either way, it seems better to use the dirty code.

**Comment by zero-plusplus** [comment]
I have released the fixed version.

I have confirmed that conditional breakpoints can be executed 20000 times without any problem.

If run the above test with the fixed version, you may notice that the performance is a few seconds slower than in `1.6.4`. This is due to `1.6.4` processing asynchronously when it should be done synchronously (i.e. a bug).

**Comment by SAbboushi** [comment]
k good solution when slower debug is acceptable
